= logdl

A tool to download log files from the SavySoda iOS TextEditor.

== Why?

I write daily log files on iPhone using https://apps.apple.com/au/app/texteditor-rich-text-editor/id296222961[the SavySoda TextEditor] — it's the simplest text editor I could find, yet containing a web server to be able to share the files; and I need to download them to my computer daily. Of course, `curl` can be used to download the files, but it involves manual work like remembering which files to get, so it's better to automate the process.

`logdl` is a tool written in Haskell that retrieves the index page, parses the file list, automatically determines the files to download (according to the rules that I need) and saves them locally. *It is still an alpha version and I'm continuing to improve it.*

The rules are: each log file contains a single day; the filename is the day of the month of the log file with the `.txt` suffix (because the TextEditor inserts it automatically), only these files are downloaded; today's log file is not downloaded; days 01…09 may also be stored in files with names 41…49 (a workaround for my other scripts).

== Building

You'll need to install https://docs.haskellstack.org/en/stable/README/[the Haskell Tool Stack] to build the project, then use `stack build`.

To run the program:

[source,bash]
----
$ stack exec logdl-exe -- --host iphone.local. --port 8082
Downloading http://iphone.local.:8082/21.txt
Downloading http://iphone.local.:8082/22.txt
Downloading http://iphone.local.:8082/23.txt
No time header for: 21, 22, 23
----

To run the tests, use `stack test`.

Used libraries:

* https://www.stackage.org/package/http-client[`http-client`] -- to work with HTTP;
* https://www.stackage.org/package/optparse-applicative[`optparse-applicative`] -- parses command-line options in the applicative functor style;
* https://www.stackage.org/package/tagsoup[`tagsoup`] -- parses any kind of HTML files into a stream of tags, it's used to parse the index page with the file list.

For testing:

* https://www.stackage.org/package/hspec[`hspec`] -- for unit testing;
* https://www.stackage.org/package/hspec-discover[`hspec-discover`] -- to automatically discover all the unit tests;
* https://www.stackage.org/package/QuickCheck[`QuickCheck`] -- for property testing.
